openapi: 3.0.1
info:
  title: bmfaudio-server
  description: File server for BMFAudio device records menage.
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification
paths:
  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
          content: {}
    post:
      tags:
        - Examples
      description: Create a new example
      requestBody:
        description: an example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleBody'
        required: true
      responses:
        200:
          description: Returns all examples
          content: {}
  /examples/{id}:
    get:
      tags:
        - Examples
      parameters:
        - name: id
          in: path
          description: The id of the example to retrieve
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Return the example with the specified id
          content: {}
        404:
          description: Example not found
          content: {}
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
  /records:
    get:
      tags:
        - Records
      description: Fetch all files
      responses:
        200:
          description: Returns files list
          content: {}
    post:
      tags:
        - Records
      description: Save the file
      responses:
        200:
          description: Returns done
          content: {}
  /records/zip:
    get:
      tags:
        - Records ZIP
      description: Fetch all files by ZIP
      responses:
        200:
          description: Returns ZIP
          content: {}
  /records/file:
    get:
      tags:
        - Singe record
      description: Fetch a singe record
      responses:
        200:
          description: Returns file
          content: {}
components:
  schemas:
    ExampleBody:
      title: example
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: no_stress
